name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            build_tool: cargo

          - target: aarch64-apple-darwin
            os: macos-latest
            build_tool: cargo

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            build_tool: cargo

          - target: i686-pc-windows-msvc
            os: windows-latest
            build_tool: cargo

          - target: aarch64-pc-windows-msvc
            os: windows-latest
            build_tool: cargo

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            build_tool: cargo

          - target: i686-unknown-linux-musl
            os: ubuntu-latest
            build_tool: cargo-zigbuild

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            build_tool: cargo-zigbuild

          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            build_tool: cargo-zigbuild

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt update -y
          sudo apt install -y musl-tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          target: ${{ matrix.target }}
          bin: fubuki
          tar: unix
          zip: windows
          build_tool: ${{ matrix.build_tool }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTUP_TOOLCHAIN: nightly
          CARGO_TERM_COLOR: always
